sources = files([
  'main.c',

  'cutscenes/story_text_cutscene.c',
  'cutscenes/kraid_rising.c',
  'cutscenes/enter_tourian.c',
  'cutscenes/statue_opening.c',
  'cutscenes/ridley_in_space.c',
  'cutscenes/before_ruins_test.c',
  'cutscenes/ridley_spawn.c',
  'cutscenes/mecha_sees_samus.c',
  'cutscenes/cutscene_utils.c',
  'cutscenes/getting_fully_powered_suit.c',
  'cutscenes/ridley_landing.c',
  'cutscenes/mother_brain_close_up.c',
  'cutscenes/samus_in_blue_ship.c',
  'sprite.c',
  'display.c',
  'init_game.c',
  'clipdata.c',
  'music_wrappers.c',
  'block.c',
  'intro.c',
  'hud_generic.c',
  'location_text.c',
  'particle.c',
  'save_file.c',
  'escape.c',
  'link.c',
  'gadora_hatch.c',
  'oam_id.c',
  'init_helpers.c',
  'audio_wrappers.c',
  'animated_graphics.c',
  'update_input.c',
  'fixed_point.c',
  'room_cutscene.c',
  'syscall_wrappers.c',
  'transfer.c',
  'sram_misc.c',
  'soft_reset.c',
  'in_game.c',
  'room_music.c',
  'save_file_load.c',
  'minimap.c',
  'ending_and_gallery.c',
  'time_attack.c',
  'fusion_gallery.c',
  'haze.c',
  'power_bomb_explosion.c',
  'dma.c',
  'chozodia_escape.c',
  'process_pause_press.c',
  'projectile.c',
  'in_game_timer.c',
  'globals1.c',
  'main.c',
  'connection.c',
  'sram/sram.c',
  'event.c',
  'color_fading.c',
  'color_effects.c',
  'scroll.c',
  'hud.c',
  'room.c',
  'text.c',
  'menus/file_select.c',
  'menus/pause_screen_map.c',
  'menus/title_screen.c',
  'menus/boot_debug.c',
  'menus/status_screen.c',
  'menus/erase_sram.c',
  'menus/game_over.c',
  'menus/pause_screen.c',
  'menus/pause_screen_sub_menus.c',
  'sprite_util.c',
  'samus.c',
  'demo.c',
  'soft_reset_input.c',
  'tourian_escape.c',
  'complex_oam.c',
  'callbacks.c',
  'in_game_cutscene.c',
  'sprites_ai/baristute.c',
  'sprites_ai/explosion_zebes_escape.c',
  'sprites_ai/gekitai_machine.c',
  'sprites_ai/crocomire.c',
  'sprites_ai/zebbo.c',
  'sprites_ai/reo.c',
  'sprites_ai/searchlight.c',
  'sprites_ai/holtz.c',
  'sprites_ai/gunship.c',
  'sprites_ai/deorem.c',
  'sprites_ai/zoomer.c',
  'sprites_ai/tangle_vine.c',
  'sprites_ai/zebetite_and_cannon.c',
  'sprites_ai/elevator_pad.c',
  'sprites_ai/sova.c',
  'sprites_ai/ruins_test.c',
  'sprites_ai/geruta.c',
  'sprites_ai/searchlight_eye.c',
  'sprites_ai/waver.c',
  'sprites_ai/morph_ball_launcher.c',
  'sprites_ai/dragon.c',
  'sprites_ai/imago_larva.c',
  'sprites_ai/morph_ball.c',
  'sprites_ai/mecha_ridley.c',
  'sprites_ai/escape_ship.c',
  'sprites_ai/mother_brain.c',
  'sprites_ai/zipline_generator.c',
  'sprites_ai/geega.c',
  'sprites_ai/skultera.c',
  'sprites_ai/unused_sprites.c',
  'sprites_ai/sidehopper.c',
  'sprites_ai/steam.c',
  'sprites_ai/security_laser.c',
  'sprites_ai/imago_cocoon.c',
  'sprites_ai/escape_ship_pirate.c',
  'sprites_ai/viola.c',
  'sprites_ai/mella.c',
  'sprites_ai/chozo_statue.c',
  'sprites_ai/boss_statues.c',
  'sprites_ai/falling_chozo_pillar.c',
  'sprites_ai/space_pirate.c',
  'sprites_ai/atomic.c',
  'sprites_ai/squeept.c',
  'sprites_ai/zeela.c',
  'sprites_ai/elevator_statue.c',
  'sprites_ai/area_banner.c',
  'sprites_ai/imago.c',
  'sprites_ai/geron.c',
  'sprites_ai/message_banner.c',
  'sprites_ai/black_space_pirate.c',
  'sprites_ai/piston.c',
  'sprites_ai/multiviola.c',
  'sprites_ai/rising_chozo_pillar.c',
  'sprites_ai/rinka.c',
  'sprites_ai/water_drop.c',
  'sprites_ai/escape_gate.c',
  'sprites_ai/zeb.c',
  'sprites_ai/unknown_item_chozo_statue.c',
  'sprites_ai/skree.c',
  'sprites_ai/dessgeega.c',
  'sprites_ai/worker_robot.c',
  'sprites_ai/space_pirate_carrying_power_bomb.c',
  'sprites_ai/enemy_drop.c',
  'sprites_ai/chozo_ball.c',
  'sprites_ai/primary_sprite_b3.c',
  'sprites_ai/power_grip.c',
  'sprites_ai/imago_larva_right_side.c',
  'sprites_ai/kraid.c',
  'sprites_ai/map_station.c',
  'sprites_ai/chozo_statue_movement.c',
  'sprites_ai/gamet.c',
  'sprites_ai/save_platform.c',
  'sprites_ai/unknown_item_block.c',
  'sprites_ai/metroid.c',
  'sprites_ai/hive.c',
  'sprites_ai/acid_worm.c',
  'sprites_ai/security_gate.c',
  'sprites_ai/save_platform_chozodia.c',
  'sprites_ai/glass_tube.c',
  'sprites_ai/ridley.c',
  'sprites_ai/gadora.c',
  'sprites_ai/parasite.c',
  'sprites_ai/polyp.c',
  'sprites_ai/ripper2.c',
  'sprites_ai/geron_norfair.c',
  'sprites_ai/charge_beam.c',
  'sprites_ai/ripper.c',
  'sprites_ai/zipline.c',
  'globals2.c',
  'screen_shake.c',
  'data/color_fading_data.c',
  'data/cutscenes/getting_fully_powered_suit_data.c',
  'data/cutscenes/enter_tourian_data.c',
  'data/cutscenes/ridley_in_space_data.c',
  'data/cutscenes/story_text_cutscene_data.c',
  'data/cutscenes/mecha_sees_samus_data.c',
  'data/cutscenes/cutscenes_data.c',
  'data/cutscenes/before_ruins_test_data.c',
  'data/cutscenes/ridley_landing_data.c',
  'data/cutscenes/statue_opening_data.c',
  'data/cutscenes/ridley_spawn_data.c',
  'data/cutscenes/samus_in_blue_ship_data.c',
  'data/cutscenes/mother_brain_close_up_data.c',
  'data/cutscenes/kraid_rising_data.c',
  'data/tourian_escape_data.c',
  'data/hatch_data.c',
  'data/projectile_data.c',
  'data/haze_data.c',
  'data/animated_graphics_data.c',
  'data/block_data.c',
  'data/fusion_gallery_data.c',
  'data/samus/samus_graphics.c',
  'data/samus/samus_animation_pointers.c',
  'data/samus/samus_empty_data.c',
  'data/samus/samus_palette_data.c',
  'data/samus/arm_cannon_data.c',
  'data/intro_data.c',
  'data/clipdata_data.c',
  'data/common_pals.c',
  'data/sprite_data.c',
  'data/nes_metroid.c',
  'data/io_transfer_data.c',
  'data/clipdata_types.c',
  'data/animated_tiles_data.c',
  'data/spriteset.c',
  'data/in_game_cutscene_data.c',
  'data/clipdata_types_tilemap.c',
  'data/save_file_data.c',
  'data/shortcut_pointers.c',
  'data/default_background_data.c',
  'data/ending_and_gallery_data.c',
  'data/cable_link_data.c',
  'data/generic_data.c',
  'data/rooms_data.c',
  'data/demo_data.c',
  'data/menus/title_screen_data.c',
  'data/menus/pause_screen_data.c',
  'data/menus/file_select_data.c',
  'data/menus/status_screen_data.c',
  'data/menus/pause_screen_sub_menus_data.c',
  'data/menus/boot_debug_data.c',
  'data/menus/erase_sram_data.c',
  'data/menus/game_over_data.c',
  'data/menus/pause_screen_map_data.c',
  'data/menus/language_select_data.c',
  'data/chozodia_escape_data.c',
  'data/samus_close_up_data.c',
  'data/sprites/baristute.c',
  'data/sprites/gekitai_machine.c',
  'data/sprites/crocomire.c',
  'data/sprites/zebbo.c',
  'data/sprites/reo.c',
  'data/sprites/searchlight.c',
  'data/sprites/holtz.c',
  'data/sprites/gunship.c',
  'data/sprites/deorem.c',
  'data/sprites/zoomer.c',
  'data/sprites/tangle_vine.c',
  'data/sprites/zebetite_and_cannon.c',
  'data/sprites/elevator_pad.c',
  'data/sprites/sova.c',
  'data/sprites/ruins_test.c',
  'data/sprites/geruta.c',
  'data/sprites/searchlight_eye.c',
  'data/sprites/waver.c',
  'data/sprites/morph_ball_launcher.c',
  'data/sprites/dragon.c',
  'data/sprites/imago_larva.c',
  'data/sprites/morph_ball.c',
  'data/sprites/mecha_ridley.c',
  'data/sprites/escape_ship.c',
  'data/sprites/mother_brain.c',
  'data/sprites/zipline_generator.c',
  'data/sprites/geega.c',
  'data/sprites/skultera.c',
  'data/sprites/unused_sprites.c',
  'data/sprites/sidehopper.c',
  'data/sprites/steam.c',
  'data/sprites/security_laser.c',
  'data/sprites/imago_cocoon.c',
  'data/sprites/viola.c',
  'data/sprites/mella.c',
  'data/sprites/chozo_statue.c',
  'data/sprites/boss_statues.c',
  'data/sprites/falling_chozo_pillar.c',
  'data/sprites/space_pirate.c',
  'data/sprites/atomic.c',
  'data/sprites/squeept.c',
  'data/sprites/zeela.c',
  'data/sprites/elevator_statue.c',
  'data/sprites/area_banner.c',
  'data/sprites/imago.c',
  'data/sprites/geron.c',
  'data/sprites/message_banner.c',
  'data/sprites/piston.c',
  'data/sprites/multiviola.c',
  'data/sprites/rising_chozo_pillar.c',
  'data/sprites/rinka.c',
  'data/sprites/escape_gate.c',
  'data/sprites/zeb.c',
  'data/sprites/unknown_item_chozo_statue.c',
  'data/sprites/skree.c',
  'data/sprites/dessgeega.c',
  'data/sprites/worker_robot.c',
  'data/sprites/space_pirate_carrying_power_bomb.c',
  'data/sprites/enemy_drop.c',
  'data/sprites/power_grip.c',
  'data/sprites/imago_larva_right_side.c',
  'data/sprites/kraid.c',
  'data/sprites/map_station.c',
  'data/sprites/gamet.c',
  'data/sprites/save_platform.c',
  'data/sprites/unknown_item_block.c',
  'data/sprites/metroid.c',
  'data/sprites/hive.c',
  'data/sprites/acid_worm.c',
  'data/sprites/security_gate.c',
  'data/sprites/save_platform_chozodia.c',
  'data/sprites/glass_tube.c',
  'data/sprites/ridley.c',
  'data/sprites/gadora.c',
  'data/sprites/parasite.c',
  'data/sprites/polyp.c',
  'data/sprites/ripper2.c',
  'data/sprites/geron_norfair.c',
  'data/sprites/charge_beam.c',
  'data/sprites/ripper.c',
  'data/sprites/zipline.c',
  'data/visual_effects_data.c',
  'data/rooms/test_rooms_data.c',
  'data/rooms/norfair/norfair_14.c',
  'data/rooms/norfair/norfair_50.c',
  'data/rooms/norfair/norfair_31.c',
  'data/rooms/norfair/norfair_35.c',
  'data/rooms/norfair/norfair_54.c',
  'data/rooms/norfair/norfair_10.c',
  'data/rooms/norfair/norfair_25.c',
  'data/rooms/norfair/norfair_44.c',
  'data/rooms/norfair/norfair_8.c',
  'data/rooms/norfair/norfair_2.c',
  'data/rooms/norfair/norfair_6.c',
  'data/rooms/norfair/norfair_40.c',
  'data/rooms/norfair/norfair_21.c',
  'data/rooms/norfair/norfair_38.c',
  'data/rooms/norfair/norfair_53.c',
  'data/rooms/norfair/norfair_32.c',
  'data/rooms/norfair/norfair_17.c',
  'data/rooms/norfair/norfair_13.c',
  'data/rooms/norfair/norfair_19.c',
  'data/rooms/norfair/norfair_36.c',
  'data/rooms/norfair/bg3.c',
  'data/rooms/norfair/norfair_1.c',
  'data/rooms/norfair/norfair_26.c',
  'data/rooms/norfair/norfair_47.c',
  'data/rooms/norfair/norfair_28.c',
  'data/rooms/norfair/norfair_43.c',
  'data/rooms/norfair/norfair_49.c',
  'data/rooms/norfair/norfair_22.c',
  'data/rooms/norfair/norfair_5.c',
  'data/rooms/norfair/norfair_33.c',
  'data/rooms/norfair/norfair_52.c',
  'data/rooms/norfair/norfair_39.c',
  'data/rooms/norfair/norfair_16.c',
  'data/rooms/norfair/norfair_18.c',
  'data/rooms/norfair/norfair_12.c',
  'data/rooms/norfair/norfair_56.c',
  'data/rooms/norfair/norfair_37.c',
  'data/rooms/norfair/norfair_0.c',
  'data/rooms/norfair/norfair_46.c',
  'data/rooms/norfair/norfair_27.c',
  'data/rooms/norfair/norfair_23.c',
  'data/rooms/norfair/norfair_48.c',
  'data/rooms/norfair/norfair_42.c',
  'data/rooms/norfair/norfair_29.c',
  'data/rooms/norfair/norfair_4.c',
  'data/rooms/norfair/norfair_15.c',
  'data/rooms/norfair/norfair_30.c',
  'data/rooms/norfair/norfair_51.c',
  'data/rooms/norfair/norfair_55.c',
  'data/rooms/norfair/norfair_34.c',
  'data/rooms/norfair/norfair_11.c',
  'data/rooms/norfair/norfair_45.c',
  'data/rooms/norfair/norfair_24.c',
  'data/rooms/norfair/norfair_3.c',
  'data/rooms/norfair/norfair_9.c',
  'data/rooms/norfair/norfair_7.c',
  'data/rooms/norfair/norfair_20.c',
  'data/rooms/norfair/norfair_41.c',
  'data/rooms/chozodia/chozodia_59.c',
  'data/rooms/chozodia/chozodia_32.c',
  'data/rooms/chozodia/chozodia_38.c',
  'data/rooms/chozodia/chozodia_53.c',
  'data/rooms/chozodia/chozodia_17.c',
  'data/rooms/chozodia/chozodia_76.c',
  'data/rooms/chozodia/chozodia_91.c',
  'data/rooms/chozodia/chozodia_19.c',
  'data/rooms/chozodia/chozodia_72.c',
  'data/rooms/chozodia/chozodia_95.c',
  'data/rooms/chozodia/chozodia_78.c',
  'data/rooms/chozodia/chozodia_13.c',
  'data/rooms/chozodia/chozodia_57.c',
  'data/rooms/chozodia/chozodia_36.c',
  'data/rooms/chozodia/chozodia_62.c',
  'data/rooms/chozodia/chozodia_85.c',
  'data/rooms/chozodia/chozodia_68.c',
  'data/rooms/chozodia/chozodia_0.c',
  'data/rooms/chozodia/chozodia_47.c',
  'data/rooms/chozodia/chozodia_26.c',
  'data/rooms/chozodia/chozodia_49.c',
  'data/rooms/chozodia/chozodia_22.c',
  'data/rooms/chozodia/chozodia_4.c',
  'data/rooms/chozodia/chozodia_28.c',
  'data/rooms/chozodia/chozodia_43.c',
  'data/rooms/chozodia/chozodia_66.c',
  'data/rooms/chozodia/chozodia_81.c',
  'data/rooms/chozodia/chozodia_14.c',
  'data/rooms/chozodia/chozodia_98.c',
  'data/rooms/chozodia/chozodia_75.c',
  'data/rooms/chozodia/chozodia_92.c',
  'data/rooms/chozodia/chozodia_31.c',
  'data/rooms/chozodia/chozodia_50.c',
  'data/rooms/chozodia/chozodia_54.c',
  'data/rooms/chozodia/chozodia_35.c',
  'data/rooms/chozodia/chozodia_71.c',
  'data/rooms/chozodia/bg3.c',
  'data/rooms/chozodia/chozodia_96.c',
  'data/rooms/chozodia/chozodia_10.c',
  'data/rooms/chozodia/chozodia_3.c',
  'data/rooms/chozodia/chozodia_44.c',
  'data/rooms/chozodia/chozodia_9.c',
  'data/rooms/chozodia/chozodia_25.c',
  'data/rooms/chozodia/chozodia_61.c',
  'data/rooms/chozodia/chozodia_86.c',
  'data/rooms/chozodia/chozodia_88.c',
  'data/rooms/chozodia/chozodia_65.c',
  'data/rooms/chozodia/chozodia_82.c',
  'data/rooms/chozodia/chozodia_21.c',
  'data/rooms/chozodia/chozodia_7.c',
  'data/rooms/chozodia/chozodia_40.c',
  'data/rooms/chozodia/chozodia_93.c',
  'data/rooms/chozodia/chozodia_74.c',
  'data/rooms/chozodia/chozodia_15.c',
  'data/rooms/chozodia/chozodia_51.c',
  'data/rooms/chozodia/chozodia_30.c',
  'data/rooms/chozodia/chozodia_34.c',
  'data/rooms/chozodia/chozodia_55.c',
  'data/rooms/chozodia/chozodia_11.c',
  'data/rooms/chozodia/chozodia_97.c',
  'data/rooms/chozodia/chozodia_70.c',
  'data/rooms/chozodia/chozodia_24.c',
  'data/rooms/chozodia/chozodia_8.c',
  'data/rooms/chozodia/chozodia_45.c',
  'data/rooms/chozodia/chozodia_2.c',
  'data/rooms/chozodia/chozodia_87.c',
  'data/rooms/chozodia/chozodia_60.c',
  'data/rooms/chozodia/chozodia_83.c',
  'data/rooms/chozodia/chozodia_64.c',
  'data/rooms/chozodia/chozodia_89.c',
  'data/rooms/chozodia/chozodia_41.c',
  'data/rooms/chozodia/chozodia_6.c',
  'data/rooms/chozodia/chozodia_20.c',
  'data/rooms/chozodia/chozodia_52.c',
  'data/rooms/chozodia/chozodia_39.c',
  'data/rooms/chozodia/chozodia_33.c',
  'data/rooms/chozodia/chozodia_58.c',
  'data/rooms/chozodia/chozodia_90.c',
  'data/rooms/chozodia/chozodia_77.c',
  'data/rooms/chozodia/chozodia_16.c',
  'data/rooms/chozodia/chozodia_12.c',
  'data/rooms/chozodia/chozodia_79.c',
  'data/rooms/chozodia/chozodia_94.c',
  'data/rooms/chozodia/chozodia_73.c',
  'data/rooms/chozodia/chozodia_18.c',
  'data/rooms/chozodia/chozodia_37.c',
  'data/rooms/chozodia/chozodia_56.c',
  'data/rooms/chozodia/chozodia_69.c',
  'data/rooms/chozodia/chozodia_84.c',
  'data/rooms/chozodia/chozodia_63.c',
  'data/rooms/chozodia/chozodia_27.c',
  'data/rooms/chozodia/chozodia_46.c',
  'data/rooms/chozodia/chozodia_1.c',
  'data/rooms/chozodia/chozodia_42.c',
  'data/rooms/chozodia/chozodia_29.c',
  'data/rooms/chozodia/chozodia_5.c',
  'data/rooms/chozodia/chozodia_23.c',
  'data/rooms/chozodia/chozodia_48.c',
  'data/rooms/chozodia/chozodia_80.c',
  'data/rooms/chozodia/chozodia_67.c',
  'data/rooms/crateria/crateria_0.c',
  'data/rooms/crateria/crateria_4.c',
  'data/rooms/crateria/crateria_12.c',
  'data/rooms/crateria/crateria_18.c',
  'data/rooms/crateria/crateria_16.c',
  'data/rooms/crateria/crateria_20.c',
  'data/rooms/crateria/crateria_3.c',
  'data/rooms/crateria/crateria_9.c',
  'data/rooms/crateria/crateria_7.c',
  'data/rooms/crateria/bg3.c',
  'data/rooms/crateria/crateria_11.c',
  'data/rooms/crateria/crateria_15.c',
  'data/rooms/crateria/crateria_21.c',
  'data/rooms/crateria/crateria_8.c',
  'data/rooms/crateria/crateria_2.c',
  'data/rooms/crateria/crateria_6.c',
  'data/rooms/crateria/crateria_10.c',
  'data/rooms/crateria/crateria_14.c',
  'data/rooms/crateria/crateria_1.c',
  'data/rooms/crateria/crateria_5.c',
  'data/rooms/crateria/crateria_19.c',
  'data/rooms/crateria/crateria_13.c',
  'data/rooms/crateria/crateria_17.c',
  'data/rooms/brinstar/brinstar_16.c',
  'data/rooms/brinstar/brinstar_4.c',
  'data/rooms/brinstar/brinstar_33.c',
  'data/rooms/brinstar/brinstar_39.c',
  'data/rooms/brinstar/brinstar_0.c',
  'data/rooms/brinstar/brinstar_37.c',
  'data/rooms/brinstar/brinstar_18.c',
  'data/rooms/brinstar/brinstar_12.c',
  'data/rooms/brinstar/brinstar_27.c',
  'data/rooms/brinstar/brinstar_23.c',
  'data/rooms/brinstar/brinstar_29.c',
  'data/rooms/brinstar/brinstar_7.c',
  'data/rooms/brinstar/brinstar_30.c',
  'data/rooms/brinstar/brinstar_15.c',
  'data/rooms/brinstar/brinstar_11.c',
  'data/rooms/brinstar/brinstar_9.c',
  'data/rooms/brinstar/bg3.c',
  'data/rooms/brinstar/brinstar_3.c',
  'data/rooms/brinstar/brinstar_34.c',
  'data/rooms/brinstar/brinstar_24.c',
  'data/rooms/brinstar/brinstar_20.c',
  'data/rooms/brinstar/brinstar_41.c',
  'data/rooms/brinstar/brinstar_31.c',
  'data/rooms/brinstar/brinstar_6.c',
  'data/rooms/brinstar/brinstar_14.c',
  'data/rooms/brinstar/brinstar_10.c',
  'data/rooms/brinstar/brinstar_35.c',
  'data/rooms/brinstar/brinstar_2.c',
  'data/rooms/brinstar/brinstar_8.c',
  'data/rooms/brinstar/brinstar_25.c',
  'data/rooms/brinstar/brinstar_40.c',
  'data/rooms/brinstar/brinstar_21.c',
  'data/rooms/brinstar/brinstar_17.c',
  'data/rooms/brinstar/brinstar_38.c',
  'data/rooms/brinstar/brinstar_32.c',
  'data/rooms/brinstar/brinstar_5.c',
  'data/rooms/brinstar/brinstar_36.c',
  'data/rooms/brinstar/brinstar_1.c',
  'data/rooms/brinstar/brinstar_13.c',
  'data/rooms/brinstar/brinstar_19.c',
  'data/rooms/brinstar/brinstar_26.c',
  'data/rooms/brinstar/brinstar_28.c',
  'data/rooms/brinstar/brinstar_22.c',
  'data/rooms/tourian/tourian_11.c',
  'data/rooms/tourian/tourian_15.c',
  'data/rooms/tourian/tourian_4.c',
  'data/rooms/tourian/tourian_0.c',
  'data/rooms/tourian/tourian_18.c',
  'data/rooms/tourian/tourian_12.c',
  'data/rooms/tourian/tourian_16.c',
  'data/rooms/tourian/bg3.c',
  'data/rooms/tourian/tourian_7.c',
  'data/rooms/tourian/tourian_3.c',
  'data/rooms/tourian/tourian_9.c',
  'data/rooms/tourian/tourian_13.c',
  'data/rooms/tourian/tourian_19.c',
  'data/rooms/tourian/tourian_17.c',
  'data/rooms/tourian/tourian_6.c',
  'data/rooms/tourian/tourian_8.c',
  'data/rooms/tourian/tourian_2.c',
  'data/rooms/tourian/tourian_10.c',
  'data/rooms/tourian/tourian_14.c',
  'data/rooms/tourian/tourian_5.c',
  'data/rooms/tourian/tourian_1.c',
  'data/rooms/ridley/ridley_6.c',
  'data/rooms/ridley/ridley_19.c',
  'data/rooms/ridley/ridley_13.c',
  'data/rooms/ridley/ridley_17.c',
  'data/rooms/ridley/ridley_2.c',
  'data/rooms/ridley/ridley_32.c',
  'data/rooms/ridley/ridley_8.c',
  'data/rooms/ridley/ridley_22.c',
  'data/rooms/ridley/ridley_28.c',
  'data/rooms/ridley/ridley_26.c',
  'data/rooms/ridley/ridley_10.c',
  'data/rooms/ridley/ridley_5.c',
  'data/rooms/ridley/ridley_1.c',
  'data/rooms/ridley/ridley_31.c',
  'data/rooms/ridley/ridley_14.c',
  'data/rooms/ridley/bg3.c',
  'data/rooms/ridley/ridley_21.c',
  'data/rooms/ridley/ridley_25.c',
  'data/rooms/ridley/ridley_11.c',
  'data/rooms/ridley/ridley_4.c',
  'data/rooms/ridley/ridley_30.c',
  'data/rooms/ridley/ridley_0.c',
  'data/rooms/ridley/ridley_15.c',
  'data/rooms/ridley/ridley_20.c',
  'data/rooms/ridley/ridley_24.c',
  'data/rooms/ridley/ridley_7.c',
  'data/rooms/ridley/ridley_12.c',
  'data/rooms/ridley/ridley_18.c',
  'data/rooms/ridley/ridley_16.c',
  'data/rooms/ridley/ridley_9.c',
  'data/rooms/ridley/ridley_3.c',
  'data/rooms/ridley/ridley_29.c',
  'data/rooms/ridley/ridley_23.c',
  'data/rooms/ridley/ridley_27.c',
  'data/rooms/kraid/kraid_39.c',
  'data/rooms/kraid/kraid_33.c',
  'data/rooms/kraid/kraid_16.c',
  'data/rooms/kraid/kraid_12.c',
  'data/rooms/kraid/kraid_18.c',
  'data/rooms/kraid/kraid_37.c',
  'data/rooms/kraid/kraid_3.c',
  'data/rooms/kraid/kraid_27.c',
  'data/rooms/kraid/kraid_9.c',
  'data/rooms/kraid/kraid_29.c',
  'data/rooms/kraid/kraid_23.c',
  'data/rooms/kraid/kraid_7.c',
  'data/rooms/kraid/kraid_15.c',
  'data/rooms/kraid/kraid_30.c',
  'data/rooms/kraid/kraid_34.c',
  'data/rooms/kraid/kraid_11.c',
  'data/rooms/kraid/bg3.c',
  'data/rooms/kraid/kraid_24.c',
  'data/rooms/kraid/kraid_0.c',
  'data/rooms/kraid/kraid_41.c',
  'data/rooms/kraid/kraid_4.c',
  'data/rooms/kraid/kraid_20.c',
  'data/rooms/kraid/kraid_14.c',
  'data/rooms/kraid/kraid_31.c',
  'data/rooms/kraid/kraid_35.c',
  'data/rooms/kraid/kraid_10.c',
  'data/rooms/kraid/kraid_1.c',
  'data/rooms/kraid/kraid_25.c',
  'data/rooms/kraid/kraid_21.c',
  'data/rooms/kraid/kraid_5.c',
  'data/rooms/kraid/kraid_40.c',
  'data/rooms/kraid/kraid_32.c',
  'data/rooms/kraid/kraid_38.c',
  'data/rooms/kraid/kraid_17.c',
  'data/rooms/kraid/kraid_19.c',
  'data/rooms/kraid/kraid_13.c',
  'data/rooms/kraid/kraid_36.c',
  'data/rooms/kraid/kraid_8.c',
  'data/rooms/kraid/kraid_26.c',
  'data/rooms/kraid/kraid_2.c',
  'data/rooms/kraid/kraid_6.c',
  'data/rooms/kraid/kraid_22.c',
  'data/rooms/kraid/kraid_28.c',
  'data/hud_data.c',
  'data/empty_datatypes.c',
  'data/tilesets/tilesets_set6.c',
  'data/tilesets/tilesets_set2.c',
  'data/tilesets/tilesets_set5.c',
  'data/tilesets/tilesets_set1.c',
  'data/tilesets/tilesets_set4.c',
  'data/tilesets/tilesets_set0.c',
  'data/tilesets/tilesets_set7.c',
  'data/tilesets/tilesets_set3.c',
  'data/text_data.c',
  'data/particle_data.c',
  'data/audio.c',
  'data/music_track_data.c',
  'multiboot.c',
  'transparency.c',
  'projectile_util.c',
  'bg_clip.c',
  'audio.c',
  'cable_link.c',
  'sprite_debris.c',
  'demo_input.c',
])
